# Generated by Django 2.1.1 on 2018-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('Score', models.IntegerField(default=0)),
            ],
        ),
    ]
