# Generated by Django 2.1.1 on 2018-09-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='code',
            new_name='passcode',
        ),
    ]
